global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'tunnel-servers'
    static_configs:
      - targets: 
        - 'tunnel-server-1:8765'
        - 'tunnel-server-2:8766'
    metrics_path: /metrics
    scrape_interval: 5s

  - job_name: 'dashboard'
    static_configs:
      - targets: ['dashboard:3000']
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:8081']
    metrics_path: /nginx_status
    scrape_interval: 10s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
